# Generated by Django 4.2 on 2024-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingarea',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
