# Generated by Django 4.2 on 2024-07-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_alter_photo_photo'),
        ('bookings', '0002_alter_bookingarea_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingarea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='areas.area', verbose_name='Площадка'),
        ),
    ]
