# Generated by Django 4.2 on 2024-07-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingarea',
            name='started',
            field=models.BooleanField(default=False, verbose_name='Начато'),
        ),
    ]
