# Generated by Django 4.2 on 2024-07-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingarea_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingarea',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
