# Generated by Django 4.2 on 2024-07-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingarea_uuid_alter_bookingarea_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporary_timeout', models.IntegerField(default=3600, verbose_name='Время жизни временной брони')),
            ],
            options={
                'verbose_name': 'Настройки брони',
                'db_table': 'bookings_settings',
            },
        ),
    ]
