# Generated by Django 4.2 on 2024-07-19 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('price', models.CharField(default='Не указана', max_length=256, verbose_name='Цена за сутки')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость человек')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='areas.area')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'area_photos',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(verbose_name='Контакт')),
                ('contact_type', models.CharField(choices=[('Email', 'Адрес электронной почты'), ('Phone', 'Телефон'), ('Instagram', 'Инстаграм'), ('Telegram', 'Телеграм'), ('Whatsapp', 'Ватсапп')], max_length=64, verbose_name='Тип контакта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата размещения')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='areas.area')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'area_contacts',
            },
        ),
    ]
