# Generated by Django 4.2 on 2024-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='length',
            field=models.PositiveIntegerField(default=100, verbose_name='Длина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='width',
            field=models.PositiveIntegerField(default=200, verbose_name='Ширина'),
            preserve_default=False,
        ),
    ]
