# Generated by Django 4.2 on 2024-07-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_area_length_area_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-created_at'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterField(
            model_name='area',
            name='price',
            field=models.CharField(default='0', max_length=256, verbose_name='Цена за сутки'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='areas.area', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='areas.area', verbose_name='Площадка'),
        ),
    ]
