# Generated by Django 4.2 on 2024-07-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_area_options_alter_area_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за сутки'),
        ),
    ]
