# Generated by Django 4.2 on 2024-07-23 01:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_alter_area_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
