# Generated by Django 4.2 on 2024-07-24 07:01

import areas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=areas.models.Photo.area_photos_path, verbose_name='Фото'),
        ),
    ]
